### ISSUE TITLE
bug: [ERR_PACKAGE_PATH_NOT_EXPORTED]

### ISSUE THREAD

**Issue by JoniXTech** [binarytf/binarytf#260] opened 2022-01-29 08:30 UTC
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Description of the bug

I got this error:

```
node:internal/modules/cjs/loader:488
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/lib/errors/DeserializerError' is not defined by "exports" in /root/bots/v7/node_modules/binarytf/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:440:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:692:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/root/bots/v7/node_modules/veza/dist/lib/Structures/MessageError.js:3:29) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

### Steps To Reproduce

1. I run `npm install`
2. The binarytf package got installed because another package needs it i think
3. when i try to run the script the error appears

### Expected behavior

I don't know what node package is installing binarytf
But then the package should work

### Additional context

Node: v16.13.1
NPM: 8.1.2
binarytf: 2.1.0

**Comment by imranbarbhuiya** [comment] 2022-01-29 10:53
duplicate of #259

**Closed** 2022-01-29 11:03 UTC
Labels: Status: Duplicate
